In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("yelp.csv")

In [3]:
df.head()

business_id        date               review_id  stars  \
0  9yKzy9PApeiPPOUJEtnvkg  2011-01-26  fWKvX83p0-ka4JS3dc6E5A      5   
1  ZRJwVLyzEJq1VAihDhYiow  2011-07-27  IjZ33sJrzXqU-0X6U8NwyA      5   
2  6oRAC4uyJCsJl1X0WZpVSA  2012-06-14  IESLBzqUCLdSzSqm0eCSxQ      4   
3  _1QQZuf4zZOyFCvXc0o6Vg  2010-05-27  G-WvGaISbqqaMHlNnByodA      5   
4  6ozycU1RpktNG2-1BroVtw  2012-01-05  1uJFq2r5QfJG_6ExMRCaGw      5   

                                                text    type  \
0  My wife took me here on my birthday for breakf...  review   
1  I have no idea why some people give bad review...  review   
2  love the gyro plate. Rice is so good and I als...  review   
3  Rosie, Dakota, and I LOVE Chaparral Dog Park!!...  review   
4  General Manager Scott Petello is a good egg!!!...  review   

                  user_id  cool  useful  funny  
0  rLtl8ZkDX5vH5nAx9C3q5Q     2       5      0  
1  0a2KyEL0d3Yb1V6aivbIuQ     0       0      0  
2  0hT2KtfLiobPvh6cDC8JQg     0       1      0  
3  uZetl9T0NcROGOyFfughhg     1       2      0  
4  vYmM4KTsC8ZfQBg-j5MWkw     0       0      0

In [4]:
df = df[["stars","text"]]

In [5]:
preprocessing = df["text"]

def firstFive(text):
    for i in range(5):
        print(preprocessing[i])
        print("------------------------")

In [6]:
firstFive(preprocessing)

My wife took me here on my birthday for breakfast and it was excellent.  The weather was perfect which made sitting outside overlooking their grounds an absolute pleasure.  Our waitress was excellent and our food arrived quickly on the semi-busy Saturday morning.  It looked like the place fills up pretty quickly so the earlier you get here the better.

Do yourself a favor and get their Bloody Mary.  It was phenomenal and simply the best I've ever had.  I'm pretty sure they only use ingredients from their garden and blend them fresh when you order it.  It was amazing.

While EVERYTHING on the menu looks excellent, I had the white truffle scrambled eggs vegetable skillet and it was tasty and delicious.  It came with 2 pieces of their griddled bread with was amazing and it absolutely made the meal complete.  It was the best "toast" I've ever had.

Anyway, I can't wait to go back!
------------------------
I have no idea why some people give bad reviews about this place. It goes to show you

In [7]:
preprocessing = df["text"].apply(lambda x: " ".join(x.lower() for x in x.split()))

In [8]:
preprocessing = preprocessing.str.replace("[^\w\s]"," ")

preprocessing

0       my wife took me here on my birthday for breakf...
1       i have no idea why some people give bad review...
2       love the gyro plate  rice is so good and i als...
3       rosie  dakota  and i love chaparral dog park  ...
4       general manager scott petello is a good egg   ...
5       quiessence is  simply put  beautiful  full win...
6       drop what you re doing and drive here  after i...
7       luckily  i didn t have to travel far to make m...
8       definitely come for happy hour  prices are ama...
9       nobuo shows his unique talents with everything...
10      the oldish man who owns the store is as sweet ...
11      wonderful vietnamese sandwich shoppe  their ba...
12      they have a limited time thing going on right ...
13      good tattoo shop  clean space  multiple artist...
14      i m 2 weeks new to phoenix  i looked up irish ...
15      was it worth the 21  for a salad and small piz...
16      we went here on a saturday afternoon and this ...
17      okay t

In [9]:
import nltk

nltk.download("stopwords")

from nltk.corpus import stopwords

preprocessing = preprocessing.apply(lambda x: " ".join(x for x in x.split() if x not in stopwords.words("english")))

[nltk_data] Downloading package stopwords to C:\Users\Muhammed
[nltk_data]     Pc\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
!pip install textblob

import textblob

from textblob import Word

nltk.download("wordnet")

preprocessing = preprocessing.apply(lambda x: " ".join(Word(i).lemmatize() for i in x.split()))

[nltk_data] Downloading package wordnet to C:\Users\Muhammed
[nltk_data]     Pc\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [11]:
preprocessing

0       wife took birthday breakfast excellent weather...
1       idea people give bad review place go show plea...
2       love gyro plate rice good also dig candy selec...
3       rosie dakota love chaparral dog park convenien...
4       general manager scott petello good egg go deta...
5       quiessence simply put beautiful full window ea...
6       drop drive ate go back next day food good cute...
7       luckily travel far make connecting flight than...
8       definitely come happy hour price amazing sake ...
9       nobuo show unique talent everything menu caref...
10      oldish man owns store sweet perhaps sweeter co...
11      wonderful vietnamese sandwich shoppe baguette ...
12      limited time thing going right bbq chicken piz...
13      good tattoo shop clean space multiple artist c...
14      2 week new phoenix looked irish bar town found...
15      worth 21 salad small pizza absolutely bad serv...
16      went saturday afternoon place incredibly empty...
17      okay b

In [12]:
df["text"] = preprocessing

In [13]:
df

stars                                               text
0         5  wife took birthday breakfast excellent weather...
1         5  idea people give bad review place go show plea...
2         4  love gyro plate rice good also dig candy selec...
3         5  rosie dakota love chaparral dog park convenien...
4         5  general manager scott petello good egg go deta...
5         4  quiessence simply put beautiful full window ea...
6         5  drop drive ate go back next day food good cute...
7         4  luckily travel far make connecting flight than...
8         4  definitely come happy hour price amazing sake ...
9         5  nobuo show unique talent everything menu caref...
10        5  oldish man owns store sweet perhaps sweeter co...
11        5  wonderful vietnamese sandwich shoppe baguette ...
12        5  limited time thing going right bbq chicken piz...
13        4  good tattoo shop clean space multiple artist c...
14        4  2 week new phoenix looked irish bar town found...
15        2  worth 21 salad small pizza absolutely bad serv...
16        3  went saturday afternoon place incredibly empty...
17        5  okay best place ever grew shopping one los gat...
18        3  met friend lunch yesterday loved water feature...
19        4  gotten better better time since review written...
20        3  dvap go least life really neat place alot hist...
21        5           place even reviewed kind place want keep
22        5  first time friend went delicious food garlic k...
23        1  u go n check car u wanna buy 1 wrong move u ev...
24        5  love place coming age favorite elsa chicken sa...
25        4  place great nice little ole fashion homemade i...
26        5  love love love place bos healthy eating recomm...
27        4  review mean much given depth reviewer chime no...
28        4  came breakfast yesterday year since stopped re...
29        4  always reliably good great beer selection well...
...     ...                                                ...
9970      5  place super cute lunch joint sloppy joe specia...
9971      5  staff great food great even cappuccino great f...
9972      4  yay even though miss living coronado glad back...
9973      5  wow went sunday around 11am busy packed roomy ...
9974      2  cowboy ciao best restaurant scottsdale cafe ca...
9975      5  lived phoenix regular fez friend probably aver...
9976      3  looking chile rellenos place great job making ...
9977      5  wait long try neighborhood hot spot father gre...
9978      5  place fabulos breakfast friend visit texas wai...
9979      5  highly recommend second time see 3 way bistec ...
9980      5  5 star great 5 happy hour special short rib ta...
9981      5  brought entire family giuseppe last night pre ...
9982      4  best corned beef sandwich anywhere anytime def...
9983      3  3 5 star decided check place wave space decor ...
9984      1  went last night whore food get basic make pizz...
9985      4  awesome food little pricey delicious loved pow...
9986      4  came december look forward next trip get tuna ...
9987      1  food delicious service discriminatory bartende...
9988      4  first time great time server knowledgable menu...
9989      5               great food service country food best
9990      5  yes rock hipster joint dig place little bit sc...
9991      5  4 star note folk rated place low must isolated...
9992      5  normally one jump reviewing chain restaurant e...
9993      4  judging review maybe went good day enjoyed tri...
9994      5  let see like surprise stadium well 9 50 tall c...
9995      3  first visit lunch today used groupon ordered b...
9996      4  called house deliciousness could go item item ...
9997      4  recently visited olive ivy business last week ...
9998      2  nephew moved scottsdale recently bunch friend ...
9999      5  4 5 location 4 5 star average think arizona re...

[10000 rows x 2 columns]

In [14]:
X = df["text"]
y = df["stars"]

In [15]:
sum(y==1),sum(y==2),sum(y==3),sum(y==4),sum(y==5)

(749, 927, 1461, 3526, 3337)

In [16]:
from sklearn.utils import resample


X_upsampled1, y_upsampled1 = resample(X[y == 1],
                                    y[y == 1],
                                    replace=True,
                                    n_samples=X[y == 4].shape[0],
                                    random_state=123)

X_upsampled2, y_upsampled2 = resample(X[y == 2],
                                     y[y == 2],
                                     replace=True,
                                     n_samples=X[y == 4].shape[0],
                                     random_state=123)

X_upsampled3, y_upsampled3 = resample(X[y == 3],
                                     y[y == 3],
                                     replace=True,
                                     n_samples=X[y == 4].shape[0],
                                     random_state=123)

X_upsampled5, y_upsampled5 = resample(X[y == 5],
                                     y[y == 5],
                                     replace=True,
                                     n_samples=X[y == 4].shape[0],
                                     random_state=123)
                                    

print('Number of class 1 examples after:', X_upsampled1.shape[0])
print('Number of class 2 examples after:', X_upsampled2.shape[0])
print('Number of class 3 examples after:', X_upsampled3.shape[0])
print('Number of class 5 examples after:', X_upsampled5.shape[0])

Number of class 1 examples after: 3526
Number of class 2 examples after: 3526
Number of class 3 examples after: 3526
Number of class 5 examples after: 3526


In [17]:
X_bal = np.hstack((X[y == 4], X_upsampled1, X_upsampled2, X_upsampled3, X_upsampled5))
y_bal = np.hstack((y[y == 4], y_upsampled1, y_upsampled2, y_upsampled3, y_upsampled5))

In [18]:
X_bal.shape[0]

17630

In [19]:
y_bal.shape[0]

17630

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = \
    train_test_split(X_bal, y_bal, 
                     test_size=0.20,
                     stratify=y_bal,
                     random_state=1)

In [21]:
df.shape

(10000, 2)

In [22]:
yelp = pd.DataFrame(X_bal,columns=["text"])

In [23]:
yelp

text
0      love gyro plate rice good also dig candy selec...
1      quiessence simply put beautiful full window ea...
2      luckily travel far make connecting flight than...
3      definitely come happy hour price amazing sake ...
4      good tattoo shop clean space multiple artist c...
5      2 week new phoenix looked irish bar town found...
6      gotten better better time since review written...
7      place great nice little ole fashion homemade i...
8      review mean much given depth reviewer chime no...
9      came breakfast yesterday year since stopped re...
10     always reliably good great beer selection well...
11     went got back phoenix gone six month one mom f...
12     must renovated place last year spacious airy l...
13     clean well thought floor plan nice friendly st...
14     mexican food simple slightly bland fairly fres...
15     decor functional staff friendly really kind to...
16     place opened next salon work amazing hit groun...
17     really really like france love clothes never a...
18     solid food great device casual environment lea...
19     son really enjoys island great food casual kid...
20     seated bar nice young man working bar provided...
21     good easy leisurely business lunch outing girl...
22     last review somewhat scathing regarding burger...
23     cliff note cheap 1 2 plate fast ready go conve...
24     idea whether japanese community part town new ...
25     got pass preview mission impossible ghost prot...
26     continuing quest identify cool locally owned p...
27     would certainly coffee shop already establishe...
28     matter order know tasty maizie lot choose litt...
29     one spot coworkers go lunch usually try get 11...
...                                                  ...
17600  love menu garlic mashed potato amazing steak m...
17601  place literally within walking distance apartm...
17602  bring flashlight dark inside read menu waiter ...
17603  one favorite bar area bar good vibe food good ...
17604  philosophical elder profession commonly say ev...
17605  great burger experience intend return next tim...
17606  better starbucks anyday staff encourage custom...
17607  love love store reduced fat chicken salad pase...
17608  went first time week ago best bbq arizona serv...
17609  dream come true traipse store toddler girl hus...
17610  true mexican street fare first little intimida...
17611  would order silvermine jimmy john day best mea...
17612  best pizza valley yet pizzaria banco great ser...
17613  another work lunch takeout place always right ...
17614  cook continues go spot without fiance like hom...
17615  went check new drop denim boy phoenicia associ...
17616  love recent cezanne show fact seen twice last ...
17617  finally well qualified well established mechan...
17618  see lot four star perhaps generous five star g...
17619  family love place anyone taken first time went...
17620  one top three dog park valley plenty room well...
17621  place gem food amazing cheap service good favo...
17622  love food spicy though luckily burned taste bu...
17623  whole market awesome like bring enough cash pi...
17624  actually visited 5 month ago liked much figure...
17625  never knew movie theater existed mean frequent...
17626  long fan aj lucky open location west side town...
17627  often driven figured go take look sometime loo...
17628  tried roy first time last night met friend rav...
17629  absolute favorite coffee shop regular friendly...

[17630 rows x 1 columns]

In [24]:
yelp2 = pd.DataFrame(y_bal,columns=["stars"])

In [25]:
yelp2

stars
0          4
1          4
2          4
3          4
4          4
5          4
6          4
7          4
8          4
9          4
10         4
11         4
12         4
13         4
14         4
15         4
16         4
17         4
18         4
19         4
20         4
21         4
22         4
23         4
24         4
25         4
26         4
27         4
28         4
29         4
...      ...
17600      5
17601      5
17602      5
17603      5
17604      5
17605      5
17606      5
17607      5
17608      5
17609      5
17610      5
17611      5
17612      5
17613      5
17614      5
17615      5
17616      5
17617      5
17618      5
17619      5
17620      5
17621      5
17622      5
17623      5
17624      5
17625      5
17626      5
17627      5
17628      5
17629      5

[17630 rows x 1 columns]

In [26]:
yelp = yelp.join(yelp2)

In [27]:
yelp

text  stars
0      love gyro plate rice good also dig candy selec...      4
1      quiessence simply put beautiful full window ea...      4
2      luckily travel far make connecting flight than...      4
3      definitely come happy hour price amazing sake ...      4
4      good tattoo shop clean space multiple artist c...      4
5      2 week new phoenix looked irish bar town found...      4
6      gotten better better time since review written...      4
7      place great nice little ole fashion homemade i...      4
8      review mean much given depth reviewer chime no...      4
9      came breakfast yesterday year since stopped re...      4
10     always reliably good great beer selection well...      4
11     went got back phoenix gone six month one mom f...      4
12     must renovated place last year spacious airy l...      4
13     clean well thought floor plan nice friendly st...      4
14     mexican food simple slightly bland fairly fres...      4
15     decor functional staff friendly really kind to...      4
16     place opened next salon work amazing hit groun...      4
17     really really like france love clothes never a...      4
18     solid food great device casual environment lea...      4
19     son really enjoys island great food casual kid...      4
20     seated bar nice young man working bar provided...      4
21     good easy leisurely business lunch outing girl...      4
22     last review somewhat scathing regarding burger...      4
23     cliff note cheap 1 2 plate fast ready go conve...      4
24     idea whether japanese community part town new ...      4
25     got pass preview mission impossible ghost prot...      4
26     continuing quest identify cool locally owned p...      4
27     would certainly coffee shop already establishe...      4
28     matter order know tasty maizie lot choose litt...      4
29     one spot coworkers go lunch usually try get 11...      4
...                                                  ...    ...
17600  love menu garlic mashed potato amazing steak m...      5
17601  place literally within walking distance apartm...      5
17602  bring flashlight dark inside read menu waiter ...      5
17603  one favorite bar area bar good vibe food good ...      5
17604  philosophical elder profession commonly say ev...      5
17605  great burger experience intend return next tim...      5
17606  better starbucks anyday staff encourage custom...      5
17607  love love store reduced fat chicken salad pase...      5
17608  went first time week ago best bbq arizona serv...      5
17609  dream come true traipse store toddler girl hus...      5
17610  true mexican street fare first little intimida...      5
17611  would order silvermine jimmy john day best mea...      5
17612  best pizza valley yet pizzaria banco great ser...      5
17613  another work lunch takeout place always right ...      5
17614  cook continues go spot without fiance like hom...      5
17615  went check new drop denim boy phoenicia associ...      5
17616  love recent cezanne show fact seen twice last ...      5
17617  finally well qualified well established mechan...      5
17618  see lot four star perhaps generous five star g...      5
17619  family love place anyone taken first time went...      5
17620  one top three dog park valley plenty room well...      5
17621  place gem food amazing cheap service good favo...      5
17622  love food spicy though luckily burned taste bu...      5
17623  whole market awesome like bring enough cash pi...      5
17624  actually visited 5 month ago liked much figure...      5
17625  never knew movie theater existed mean frequent...      5
17626  long fan aj lucky open location west side town...      5
17627  often driven figured go take look sometime loo...      5
17628  tried roy first time last night met friend rav...      5
17629  absolute favorite coffee shop regular friendly...      5

[17630 rows x 2 columns]

In [28]:
df = yelp.copy()

In [29]:
df

text  stars
0      love gyro plate rice good also dig candy selec...      4
1      quiessence simply put beautiful full window ea...      4
2      luckily travel far make connecting flight than...      4
3      definitely come happy hour price amazing sake ...      4
4      good tattoo shop clean space multiple artist c...      4
5      2 week new phoenix looked irish bar town found...      4
6      gotten better better time since review written...      4
7      place great nice little ole fashion homemade i...      4
8      review mean much given depth reviewer chime no...      4
9      came breakfast yesterday year since stopped re...      4
10     always reliably good great beer selection well...      4
11     went got back phoenix gone six month one mom f...      4
12     must renovated place last year spacious airy l...      4
13     clean well thought floor plan nice friendly st...      4
14     mexican food simple slightly bland fairly fres...      4
15     decor functional staff friendly really kind to...      4
16     place opened next salon work amazing hit groun...      4
17     really really like france love clothes never a...      4
18     solid food great device casual environment lea...      4
19     son really enjoys island great food casual kid...      4
20     seated bar nice young man working bar provided...      4
21     good easy leisurely business lunch outing girl...      4
22     last review somewhat scathing regarding burger...      4
23     cliff note cheap 1 2 plate fast ready go conve...      4
24     idea whether japanese community part town new ...      4
25     got pass preview mission impossible ghost prot...      4
26     continuing quest identify cool locally owned p...      4
27     would certainly coffee shop already establishe...      4
28     matter order know tasty maizie lot choose litt...      4
29     one spot coworkers go lunch usually try get 11...      4
...                                                  ...    ...
17600  love menu garlic mashed potato amazing steak m...      5
17601  place literally within walking distance apartm...      5
17602  bring flashlight dark inside read menu waiter ...      5
17603  one favorite bar area bar good vibe food good ...      5
17604  philosophical elder profession commonly say ev...      5
17605  great burger experience intend return next tim...      5
17606  better starbucks anyday staff encourage custom...      5
17607  love love store reduced fat chicken salad pase...      5
17608  went first time week ago best bbq arizona serv...      5
17609  dream come true traipse store toddler girl hus...      5
17610  true mexican street fare first little intimida...      5
17611  would order silvermine jimmy john day best mea...      5
17612  best pizza valley yet pizzaria banco great ser...      5
17613  another work lunch takeout place always right ...      5
17614  cook continues go spot without fiance like hom...      5
17615  went check new drop denim boy phoenicia associ...      5
17616  love recent cezanne show fact seen twice last ...      5
17617  finally well qualified well established mechan...      5
17618  see lot four star perhaps generous five star g...      5
17619  family love place anyone taken first time went...      5
17620  one top three dog park valley plenty room well...      5
17621  place gem food amazing cheap service good favo...      5
17622  love food spicy though luckily burned taste bu...      5
17623  whole market awesome like bring enough cash pi...      5
17624  actually visited 5 month ago liked much figure...      5
17625  never knew movie theater existed mean frequent...      5
17626  long fan aj lucky open location west side town...      5
17627  often driven figured go take look sometime loo...      5
17628  tried roy first time last night met friend rav...      5
17629  absolute favorite coffee shop regular friendly...      5

[17630 rows x 2 columns]

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17630 entries, 0 to 17629
Data columns (total 2 columns):
text     17630 non-null object
stars    17630 non-null int64
dtypes: int64(1), object(1)
memory usage: 275.5+ KB


In [31]:
df.groupby("stars").describe()

text                                                               
      count unique                                                top freq
stars                                                                     
1      3526    744  could give zero star would worst experience fr...   14
2      3526    910  live close stop eating service slow friend com...   12
3      3526   1334  went last night bf another couple really high ...    9
4      3526   3526  going niro several year always count fulfillin...    1
5      3526   2191  favorite starbucks mesa even closest one home ...    6

In [32]:
X = df["text"]
y = df["stars"]

In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv = CountVectorizer()

X = cv.fit_transform(X)

In [35]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [37]:
from sklearn.metrics import classification_report,confusion_matrix


              precision    recall  f1-score   support

           1       0.84      0.88      0.86      1052
           2       0.82      0.79      0.80      1120
           3       0.68      0.73      0.70      1034
           4       0.57      0.57      0.57      1060
           5       0.70      0.64      0.67      1023

   micro avg       0.72      0.72      0.72      5289
   macro avg       0.72      0.72      0.72      5289
weighted avg       0.72      0.72      0.72      5289



In [38]:
print(confusion_matrix(y_test,predictions))

[[929  71  41   5   6]
 [ 84 885  91  42  18]
 [ 41  58 754 139  42]
 [ 27  51 165 604 213]
 [ 30  14  57 267 655]]


In [50]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier

In [40]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    print(classification_report(y_test,predictions)) 

In [48]:
get_score(MultinomialNB() , X_train, X_test, y_train, y_test) #Naive Bayes

              precision    recall  f1-score   support

           1       0.84      0.88      0.86      1052
           2       0.82      0.79      0.80      1120
           3       0.68      0.73      0.70      1034
           4       0.57      0.57      0.57      1060
           5       0.70      0.64      0.67      1023

   micro avg       0.72      0.72      0.72      5289
   macro avg       0.72      0.72      0.72      5289
weighted avg       0.72      0.72      0.72      5289



In [41]:
get_score(SVC(), X_train, X_test, y_train, y_test) #Support Vector Machine

D:\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


              precision    recall  f1-score   support

           1       0.59      0.16      0.25      1052
           2       0.00      0.00      0.00      1120
           3       0.29      0.07      0.11      1034
           4       0.00      0.00      0.00      1060
           5       0.21      0.98      0.35      1023

   micro avg       0.24      0.24      0.24      5289
   macro avg       0.22      0.24      0.14      5289
weighted avg       0.22      0.24      0.14      5289



D:\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [42]:
get_score(LogisticRegression(), X_train, X_test, y_train, y_test) #Logistic Regression

D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


              precision    recall  f1-score   support

           1       0.93      1.00      0.96      1052
           2       0.91      0.94      0.92      1120
           3       0.81      0.86      0.83      1034
           4       0.66      0.48      0.55      1060
           5       0.70      0.78      0.74      1023

   micro avg       0.81      0.81      0.81      5289
   macro avg       0.80      0.81      0.80      5289
weighted avg       0.80      0.81      0.80      5289

None


In [43]:
get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test) #RandomForest

              precision    recall  f1-score   support

           1       0.93      0.99      0.96      1052
           2       0.95      0.94      0.95      1120
           3       0.87      0.85      0.86      1034
           4       0.64      0.61      0.63      1060
           5       0.73      0.75      0.74      1023

   micro avg       0.83      0.83      0.83      5289
   macro avg       0.83      0.83      0.83      5289
weighted avg       0.83      0.83      0.83      5289

None


In [1]:
get_score(KNeighborsClassifier(n_neighbors=5,metric='minkowski') , X_train, X_test, y_train, y_test) #KNeighborsClassifier

NameError: name 'get_score' is not defined

In [44]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [45]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [57]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(X,y):
    X_train, X_test, y_train, y_test = X[train_index], X[test_index], \
                                       y[train_index], y[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

              precision    recall  f1-score   support

           1       0.92      0.97      0.94      1176
           2       0.90      0.92      0.91      1176
           3       0.79      0.84      0.81      1176
           4       0.61      0.48      0.54      1176
           5       0.70      0.76      0.73      1176

   micro avg       0.79      0.79      0.79      5880
   macro avg       0.78      0.79      0.79      5880
weighted avg       0.78      0.79      0.79      5880

              precision    recall  f1-score   support

           1       0.74      0.13      0.22      1176
           2       0.95      0.02      0.03      1176
           3       0.29      0.07      0.11      1176
           4       0.19      0.02      0.03      1176
           5       0.22      0.97      0.35      1176

   micro avg       0.24      0.24      0.24      5880
   macro avg       0.48      0.24      0.15      5880
weighted avg       0.48      0.24      0.15      5880

              precisio

In [58]:
scores_logistic

[None, None, None]

In [59]:
scores_svm

[None, None, None]

In [60]:
scores_rf

[None, None, None]

In [52]:
from sklearn.model_selection import cross_val_score

In [63]:
scores = cross_val_score(RandomForestClassifier(n_estimators=40), X, y, cv=20)

In [64]:
scores

array([0.86101695, 0.88474576, 0.86101695, 0.89039548, 0.88700565,
       0.89039548, 0.8875    , 0.87613636, 0.86477273, 0.87386364,
       0.86136364, 0.875     , 0.85454545, 0.86363636, 0.87159091,
       0.89431818, 0.85795455, 0.87727273, 0.86818182, 0.86022727])